import { EmployeeData } from "./EmployeeData"
export const empData: EmployeeData[] = [
    {
        id: 1,
        name: "Ramesh",
        department: "Development",
        age: 24,
        userId: 284,
    },
    {
        id: 2,
        name: "Suresh",
        department: "QA",
        age: 37,
        userId: 254,
    },
    {
        id: 3,
        name: "Ganesh",
        department: "QA",
        age: 32,
        userId: 234,
    },
    {
        id: 4,
        name: "Ganpat",
        department: "Testing",
        age: 24,
        userId: 281,
    },
    {
        id: 5,
        name: "Sayli",
        department: "Development",
        age: 21,
        userId: 280,
    },
    {
        id: 6,
        name: "Megha",
        department: "QA",
        age: 24,
        userId: 270,
    },
    {
        id: 7,
        name: "Priyanka",
        department: "Testing",
        age: 33,
        userId: 266,
    },
    {
        id: 8,
        name: "Sandesh",
        department: "Development",
        age: 24,
        userId: 273,
    },
    {
        id: 9,
        name: "Kashiram",
        department: "QA",
        age: 25,
        userId: 277,
    },
    {
        id: 10,
        name: "Manish",
        department: "Testing",
        age: 26,
        userId: 278,
    },
    {
        id: 11,
        name: "Madhuri",
        department: "Testing",
        age: 23,
        userId: 279,
    },
    {
        id: 12,
        name: "Shubhankar",
        department: "Development",
        age: 22,
        userId: 285,
    },
    {
        id: 13,
        name: "Anuraj",
        department: "QA",
        age: 24,
        userId: 288,
    },
    {
        id: 14,
        name: "Ram",
        department: "Development",
        age: 24,
        userId: 289,
    },
    {
        id: 15,
        name: "Omkar",
        department: "Testing",
        age: 24,
        userId: 290,
    },
    {
        id: 16,
        name: "Pradynesh",
        department: "Development",
        age: 25,
        userId: 293,
    },
    {
        id: 17,
        name: "Prathamesh",
        department: "QA",
        age: 24,
        userId: 294,
    },
    {
        id: 18,
        name: "Jayesh",
        department: "Testing",
        age: 24,
        userId: 295,
    },
    {
        id: 19,
        name: "Aniksha",
        department: "Development",
        age: 24,
        userId: 296,
    },
    {
        id: 20,
        name: "Chintan",
        department: "Development",
        age: 24,
        userId: 299,
    },
]